### PR TITLE
Sawtooth SDK for .NET Core

### PR DESCRIPTION
**Pull request by tmarkovski**
Sawtooth SDK for .NET Core

This is a .NET implementation of the SDK. It features full support for the client libraries. The SDK targets netstandard2.0, making it usable in all .NET Core applications, including mobile frameworks like Xamarin.

Features
- Transaction Processor
  - ITransactionHandler interface - main handler implementation 
  - TransactionContext - provides access to methods for managing the state as well as events and receipt data
- Client modules
  - ISigner and Signer implementation - support for signing and verifying signatures. Signer class also includes methods for generating key pairs
  - ValidatorClient - class that wraps access to the ZMQ based on the same stream logic as the transaction processor. Provides method to get/submit batches and transactions as well as sending any message

The SDK uses the Task Parallel Library to provide idiomatic method signatures for working with request/response messaging.

Dependencies
- BouncyCastle
- Google.Protobuf
- NetMQ

Examples
Two projects implementing the "intkey" processor family are included in the examples as well as a tutorial on running the code.

Protobufs
Protobufs are generated using Google.Protobuf.Tools package that provides "protoc" binaries for all platforms.

Unit Tests
Basic unit tests with xUnit are included. Better code coverage with additional unit tests will be added soon.

Signed-off-by: Tomislav Markovski <tmarkovski@gmail.com>

### CODE REVIEW

**Comment by ryjones** [comment]
BoncyCastle->BouncyCastle

**Comment by vaporos** [comment]
Please add license headers on the top of all the source files.

**Comment by tmarkovski** [comment]
@vaporos Added

**Review by vaporos — APPROVED** [review]

**Review by aludvik — APPROVED** [review]

**Comment by dcmiddle** [comment]
@tmarkovski Looks like I'm late to the party.
Great contribution!
Can you fix the license headers? Unless Intel provided these files, you don't need the intel copyright at the top of each.

**Pull request merged**
